const API_ENDPOINTS = {
  LOGIN: '/api/drm/login',
  LOGOUT: '/api/user/logout',
  LOGIN_PORTAL:
    process.env.REACT_APP_LOGIN_SOURCE ||
    'https://loginportal.thisisdevmar.com/',
  USER: '/api/user',
  ACTIVE_PROPERTIES: '/api/drm/getproperties/active',
  ALL_CELLS: '/api/amp/all',
  CREATE_CELLS_BULK: '/api/amp/bulkcreate',
  UPDATE_CELLS_BULK: '/api/amp/bulkupdate',
  SET_CELLS_BULK: '/api/amp/bulk_column',
  BULK_COLUMNS: (username, year) => `/api/amp/bulk_columns/${username}/${year}`,
  AMP_GROUPS_MAPPING: '/api/amp/mapping/groups',
  GET_TODAYS_ACTIONS: '/api/action/all/today',
  GET_UNSCHEDULED_ISSUES: '/api/issue/unscheduled',
  SCHEDULE_ACTION: '/api/action/schedule',
  CREATE_ACTION: '/api/action/create',
  DRM_DEALS: '/api/drm/deals',
  ISSUE_CREATE: '/api/issue/create',
  ISSUE_UPDATE: '/api/issue/update',
  GET_ALL_ISSUE_TAGS: '/api/tags/issue/all',
  DELETE_TAG: '/api/tags/remove',
  ADD_TAG: '/api/tags/add',
  GET_ALL_ACTION_TAGS: '/api/tags/action/all',
  DELETE_ACTION_TAG_FROM_ACTION: '/api/tags/remove/action',
  ADD_ACTION_TAG_TO_ACTION: '/api/tags/add/action',
  UPLOAD_FILE: '/api/file/create',
  GET_FILES: (tableName, parentId) => `/api/file/${tableName}/${parentId}`,
  GET_MULTIPLE_FILES: (tableName, parentId) =>
    `/api/file/${tableName}/all?parent_id=${parentId}`,
  DELETE_FILE: id => `/api/file/delete/${id}`,
  ASSOCIATE_FILES: '/api/file/create/associations',
  DRM_USERS: '/api/drm/users',
  DRM_GROUPS: '/api/drm/groups',
  DRM_RECORDSEARCH: searchTerm => `/api/drm/recordsearch2?query=${searchTerm}`,
  ESTIMATE_ISSUE: '/api/estimates',
  INVOICE_ISSUE: '/api/invoices',
  UPDATE_ACTION: id => `/api/action/update/${id}`,
  GET_ISSUE_HISTORY: id => `/api/history/${id}`,
  GET_ISSUE_OWNER_MESSAGE: id => `/api/ownermessages/${id}`,
  CREATE_OR_UPDATE_OWNER_MESSAGE: '/api/ownermessages/create',
  SEND_NOTIFY_OWNER_MESSAGE: id => `/api/ownermessages/send/${id}`,
  DEASSOCIATE_FILE: id => `/api/file/delete/association/${id}`,
  GET_UNRESOLVED_ISSUES: `/api/issue/resolved`,
  ARCHIVE_ISSUE: `/api/issue/archive`,
  RESOLVE_ISSUE: `/api/issue/resolve`,
  GET_ALL_ISSUES: `/api/issue/all`,
  DELETE_INVOICE: issueId => `/api/invoices/${issueId}`,
  REVISE_ESTIMATE: issueId => `/api/estimates/revise/${issueId}`,
  DELETE_ESTIMATE: issueId => `/api/estimates/${issueId}`,
  REVISE_INVOICE: issueId => `/api/invoices/revise/${issueId}`,
  SYNC_FILE_ASSOCIATIONS: tableName => `/api/file/sync/associations/${tableName}`,
};

export default API_ENDPOINTS;
