export const WINDOW_RESIZED = 'WINDOW_RESIZED';

export const FETCHING_ACTIVE_PROPERTIES = 'FETCHING_ACTIVE_PROPERTIES';
export const FETCHING_ACTIVE_PROPERTIES_SUCCESS =
  'FETCHING_ACTIVE_PROPERTIES_SUCCESS';
export const FETCHING_ACTIVE_PROPERTIES_FAILURE =
  'FETCHING_ACTIVE_PROPERTIES_FAILURE';

export const FETCHING_CELLS = 'FETCHING_CELLS';
export const FETCHING_CELLS_SUCCESS = 'FETCHING_CELLS_SUCCESS';
export const FETCHING_CELLS_FAILURE = 'FETCHING_CELLS_FAILURE';

export const UPDATING_CELLS = 'UPDATING_CELLS';
export const UPDATING_CELLS_SUCCESS = 'UPDATED_CELLS_SUCCESS';
export const UPDATING_CELLS_FAILURE = 'UPDATED_CELLSS_FAILURE';

export const CREATING_CELLS = 'UPDATING_CELLS';
export const CREATING_CELLS_SUCCESS = 'CREATED_CELLS_SUCCESS';
export const CREATING_CELLS_FAILURE = 'CREATED_CELLS_FAILURE';

export const FETCHING_BULK_COLUMNS = 'FETCHING_BULK_COLUMNS';
export const FETCHING_BULK_COLUMNS_SUCCESS = 'FETCHING_BULK_COLUMNS_SUCCESS';
export const FETCHING_BULK_COLUMNS_FAILURE = 'FETCHING_BULK_COLUMNS_FAILURE';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAILURE = 'AUTH_USER_FAILURE';

export const FETCHING_USER = 'FETCHING_USER';
export const FETCHED_USER_SUCCESS = 'FETCHED_USER_SUCCESS';
export const FETCHED_USER_FAILURE = 'FETCHED_USER_FAILURE';

export const FETCHING_PW_RESET = 'FETCHING_PW_RESET';
export const FETCHED_PW_RESET_SUCCESS = 'FETCHED_PW_RESET_SUCCESS';
export const FETCHED_PW_RESET_FAILURE = 'FETCHED_PW_RESET_FAILURE';

export const FETCHING_CHANGE_PW = 'FETCHING_CHANGE_PW';
export const FETCHED_CHANGE_PW_SUCCESS = 'FETCHED_CHANGE_PW_SUCCESS';
export const FETCHED_CHANGE_PW_FAILURE = 'FETCHED_CHANGE_PW_FAILURE';

export const FETCHING_TODAYS_ACTIONS = 'FETCHING_TODAYS_ACTIONS';
export const FETCHING_TODAYS_ACTIONS_SUCCESS =
  'FETCHING_TODAYS_ACTIONS_SUCCESS';
export const FETCHING_TODAYS_ACTIONS_FAILURE =
  'FETCHING_TODAYS_ACTIONS_FAILURE';

export const UPDATING_ONE_ACTION = 'UPDATING_ONE_ACTION';
export const UPDATING_ONE_ACTION_SUCCESS = 'UPDATING_ONE_ACTION_SUCCESS';
export const UPDATING_ONE_ACTION_FAILURE = 'UPDATING_ONE_ACTION_FAILURE';

export const FETCHING_UNSCHEDULED_ISSUES = 'FETCHING_UNSCHEDULED_ISSUES';
export const FETCHING_UNSCHEDULED_ISSUES_SUCCESS =
  'FETCHING_UNSCHEDULED_ISSUES_SUCCESS';
export const FETCHING_UNSCHEDULED_ISSUES_FAILURE =
  'FETCHING_UNSCHEDULED_ISSUES_FAILURE';

export const FETCHING_RESOLVED_ISSUES = 'FETCHING_RESOLVED_ISSUES';
export const FETCHING_RESOLVED_ISSUES_SUCCESS =
  'FETCHING_RESOLVED_SUCCESS';
export const FETCHING_RESOLVED_ISSUES_FAILURE =
  'FETCHING_RESOLVED_FAILURE';

export const FETCHING_AMP_GROUPS_MAPPING = 'FETCHING_AMP_GROUPS_MAPPING';
export const FETCHING_AMP_GROUPS_MAPPING_SUCCESS =
  'FETCHING_AMP_GROUPS_MAPPING_SUCCESS';
export const FETCHING_AMP_GROUPS_MAPPING_FAILURE =
  'FETCHING_AMP_GROUPS_MAPPING_FAILURE';

export const FETCHING_DRM_USERS = 'FETCHING_DRM_USERS';
export const FETCHING_DRM_USERS_SUCCESS = 'FETCHING_DRM_USERS_SUCCESS';
export const FETCHING_DRM_USERS_FAILURE = 'FETCHING_DRM_USERS_FAILURE';

export const FETCHING_TAGS = 'FETCHING_ALL_TAGS';
export const FETCHING_TAGS_SUCCESS = 'FETCHING_ALL_TAGS_SUCCESS';
export const FETCHING_TAGS_FAILURE = 'FETCHING_ALL_TAGS_FAILURE';

export const REMOVING_ONE_TAG = 'REMOVING_ONE_TAG';
export const REMOVING_ONE_TAG_SUCCESS = 'REMOVING_ONE_TAG_SUCCESS';
export const REMOVING_ONE_TAG_FAILURE = 'REMOVING_ONE_TAG_FAILURE';

export const ADDING_ONE_TAG = 'ADDING_ONE_TAG';
export const ADDING_ONE_TAG_SUCCESS = 'ADDING_ONE_TAG_SUCCESS';
export const ADDING_ONE_TAG_FAILURE = 'ADDING_ONE_TAG_FAILURE';

export const PW_RESET_INITIAL = 'PW_RESET_INITIAL';

export const OPEN_NOTIFICATION = 'OPEN_NOTIFICATION';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';

export const DELMAR_TOKEN = 'DELMAR_TOKEN';

export const FETCHING_FILES = 'FETCHING_FILES';
export const FETCHED_FILES_SUCCESS = 'FETCHED_FILES_SUCCESS';
export const FETCHED_FILES_FAILURE = 'FETCHED_FILES_FAILURE';

export const UPLOADING_FILE = 'UPLOADING_FILE';
export const UPLOADED_FILE_SUCCESS = 'UPLOADED_FILE_SUCCESS';
export const UPLOADED_FILE_FAILURE = 'UPLOADED_FILE_FAILURE';

export const FETCHING_DRM_DEALS = 'FETCHING_DRM_DEALS';
export const FETCHING_DRM_DEALS_SUCCESS = 'FETCHING_DRM_DEALS_SUCCESS';
export const FETCHING_DRM_DEALS_FAILURE = 'FETCHING_DRM_DEALS_FAILURE';

export const FETCHING_DRM_GROUPS = 'FETCHING_DRM_GROUPS';
export const FETCHING_DRM_GROUPS_SUCCESS = 'FETCHING_DRM_GROUPS_SUCCESS';
export const FETCHING_DRM_GROUPS_FAILURE = 'FETCHING_DRM_GROUPS_FAILURE';

export const OPEN_GALLERY = 'OPEN_GALLERY';
export const CLOSE_GALLERY = 'CLOSE_GALLERY';

export const DELETING_FILE = 'DELETING_FILE';
export const DELETING_FILES_SUCCESS = 'DELETING_FILES_SUCCESS';
export const DEASSOCIATING_FILE_SUCCESS = 'DEASSOCIATING_FILE_SUCCESS';
export const DELETING_FILES_FAILURE = 'DELETING_FILES_FAILURE';
export const FLUSH_FILES = 'PRE_SYNCING_FILES';

export const BASE_DRM_URL =
  process.env.REACT_APP_DRM_URL || 'https://telemetry.thisisdevmar.com';

export const FETCHING_ESTIMATE = 'FETCHING_ESTIMATE';
export const FETCHING_ESTIMATE_SUCCESS = 'FETCHING_ESTIMATE_SUCCESS';
export const FETCHING_ESTIMATE_FAILURE = 'FETCHING_ESTIMATE_FAILURE';

export const FETCHING_INVOICE = 'FETCHING_INVOICE';
export const FETCHING_INVOICE_SUCCESS = 'FETCHING_INVOICE_SUCCESS';
export const FETCHING_INVOICE_FAILURE = 'FETCHING_INVOICE_FAILURE';

export const ACTION_REQUIRED = 'ACTION_REQUIRED';
export const NEW_ISSUES = 'NEW_ISSUES';
export const UNSCHEDULED_ISSUES = 'UNSCHEDULED_ISSUES';
export const SCHEDULED_ISSUES = 'SCHEDULED_ISSUES';
export const ALL_ISSUES = 'ALL_ISSUES';
export const ESTIMATES_ISSUES = 'ESTIMATES_ISSUES';

export const RESOLVED = 'RESOLVED';

export const INVOICE_ISSUES = 'INVOICE_ISSUES';
export const NOTIFY_OWNER_ISSUES = 'NOTIFY_OWNER_ISSUES';

export const FETCHING_HISTORY = 'FETCHING_HISTORY';
export const FETCHING_HISTORY_SUCCESS = 'FETCHING_HISTORY_SUCCESS';
export const FETCHING_HISTORY_FAILURE = 'FETCHING_HISTORY_FAILURE';

export const FETCHING_OWNER_MESSAGE = 'FETCHING_OWNER_MESSAGE';
export const FETCHING_OWNER_MESSAGE_SUCCESS = 'FETCHING_OWNER_MESSAGE_SUCCESS';
export const FETCHING_OWNER_MESSAGE_FAILURE = 'FETCHING_OWNER_MESSAGE_FAILURE';

export const ARCHIVING_ONE_ISSUE = 'ARCHIVING_ONE_ISSUE';
export const ARCHIVING_ONE_ISSUE_SUCCESS = 'ARCHIVING_ONE_ISSUE_SUCCESS';
export const ARCHIVING_ONE_ISSUE_FAILURE = 'ARCHIVING_ONE_ISSUE_FAILURE';

export const RESOLVING_ONE_ISSUE = 'RESOLVING_ONE_ISSUE';
export const RESOLVING_ONE_ISSUE_SUCCESS = 'RESOLVING_ONE_ISSUE_SUCCESS';
export const RESOLVING_ONE_ISSUE_FAILURE = 'RESOLVING_ONE_ISSUE_FAILURE';

export const FETCHING_ALL_ISSUES = 'FETCHING_ALL_ISSUES';
export const FETCHING_ALL_ISSUES_SUCCESS = 'FETCHING_ALL_ISSUES_SUCCESS';
export const FETCHING_ALL_ISSUES_FAILURE = 'FETCHING_ALL_ISSUES_FAILURE';
